spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://212.132.97.24:5432/dostapchenko}
    username: ${DATABASE_USERNAME:dostapchenko}
    password: ${DATABASE_PASSWORD:ARa89WdM0ZnD}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
