spring:
  profiles:
    include: datasource
  application:
    name: ${APPLICATION_NAME}

server:
  servlet:
    context-path: /api
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_MILLIS:3600000}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION_MILLIS:3600000}
